name: edstaq_31_07_2025
description: "EDSTAQ - The Learning Network"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/icon.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
  
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 3.0.1+22

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_cached_pdfview: ^0.4.2
  change_case: ^2.2.0
  flutter_svg: ^2.2.0
  google_nav_bar: ^5.0.6
  another_carousel_pro: ^1.0.0
  youtube_player_flutter: ^9.1.1
  marquee: ^2.2.3
  # enhanced_url_launcher: ^6.1.10
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  # flutter_share: ^2.0.0
  share_plus: ^11.0.0
  package_info_plus: ^8.3.0
  cached_network_image: ^3.0.0
  email_validator: ^3.0.0
  google_sign_in: ^6.1.6
  # .....making some errors
  device_info_plus: ^11.5.0
  firebase_auth: ^6.0.0
  google_mobile_ads: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  get: ^4.6.6
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  jumping_dot: ^0.0.7
  win32: ^5.5.4
  url_launcher: ^6.3.2
  # 
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0


  # flutter_launcher_icons: ^0.14.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.svg
    - assets/menu.svg
    - assets/notification.svg
    - assets/request.svg
    - assets/search.svg
    - assets/drawerheader.svg
    - assets/file.svg
    - assets/youtube.svg
    - assets/pdf.svg
    - assets/login_illustrate.png
    - assets/mobile_verification.png
    - assets/three_dot.svg
    - assets/temp_login_image.png
    - assets/update_image.png
    - assets/bot.svg
    - assets/white_logo.svg
    - assets/blue_logo.svg




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 900
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
    - family: Nunitoans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
    - family: cuicons
      fonts:
        - asset: assets/fonts/icons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# flutter_icons:
#   android: true
#   ios: true
#   image_path: assets/making/logo.png
#   adaptive_icon_background: assets/making/ic_launcher_background.png
#   adaptive_icon_foreground: assets/making/ic_launcher_foreground.png



